dingding:
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dingding
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    user-secret-kry: 20220813
    user-t-tL: 7200000
    user-token-name: token
  logging:
    level:
      com:
        sky:
          controller: info
          mapper: debug
          service: info
