server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dingdinguse&Unicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.apache.ibatis: debug
