server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      sky:
        controller: info
        mapper: debug
        service: info

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dingding
    driver-class-name: com.mysql.cj.jdbc.Driver
